version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/rag_api"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/embedding_pipeline"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/document_processor"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/ocr_service"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/infrastructure"
    schedule:
      interval: "weekly"
