"""Database query handler — generates, validates, and executes SQL.

Used by the routing layer for queries classified as 'database' or 'hybrid'.
SQL is generated by Claude Sonnet, validated for safety, then executed
against PostgreSQL via asyncpg.
"""

from __future__ import annotations

import json
import logging
import re
import time

import anthropic
import asyncpg

logger = logging.getLogger(__name__)

SQL_GEN_MODEL = "claude-sonnet-4-6"
TENANT_ID = "kent_sd"
MAX_ROWS = 50

SQL_GEN_SYSTEM_PROMPT = """\
You are a SQL query generator for a school district document database (PostgreSQL).

Available tables:
- documents: id (UUID), tenant_id (VARCHAR), title (TEXT), document_type (VARCHAR: \
'agenda_item', 'agenda', 'attachment'), meeting_date (DATE), committee_name (VARCHAR), \
source_url (TEXT), content_text (TEXT), processing_status (VARCHAR), created_at (TIMESTAMPTZ)
- chunks: id (UUID), tenant_id (VARCHAR), document_id (UUID FK->documents.id), \
chunk_index (INT), content (TEXT), token_count (INT), embedding_status (VARCHAR)
- tenants: tenant_id (VARCHAR), name (VARCHAR)

Rules:
- ALWAYS include WHERE tenant_id = $1 (parameter will be 'kent_sd')
- Use $N for parameters (asyncpg convention), starting from $2 for user-provided values
- Return ONLY valid JSON: {"sql": "SELECT ...", "params": ["kent_sd", ...], \
"explanation": "..."}
- Use ILIKE for text searches
- LIMIT results to 50
- Never use INSERT, UPDATE, DELETE, DROP, or any DDL
- For date ranges: meeting_date >= $N AND meeting_date <= $N
- For person name searches: use content_text ILIKE '%' || $N || '%' on documents, \
or content ILIKE '%' || $N || '%' on chunks
- For counting meetings, count DISTINCT meeting_date values (multiple documents per meeting)
- Always alias aggregate columns for clarity"""

# Tokens that must NEVER appear in generated SQL
_FORBIDDEN_TOKENS = re.compile(
    r"\b(INSERT|UPDATE|DELETE|DROP|ALTER|CREATE|TRUNCATE|GRANT|REVOKE|EXECUTE)\b",
    re.IGNORECASE,
)


def validate_sql(sql: str) -> bool:
    """Check that SQL is a safe read-only SELECT query.

    Returns True if safe, False otherwise.
    """
    stripped = sql.strip()

    # Must start with SELECT
    if not stripped.upper().startswith("SELECT"):
        logger.warning("SQL validation failed: does not start with SELECT")
        return False

    # No multi-statement (semicolons)
    if ";" in stripped:
        logger.warning("SQL validation failed: contains semicolon (multi-statement)")
        return False

    # No SQL comments that could hide injection
    if "--" in stripped:
        logger.warning("SQL validation failed: contains -- comment")
        return False

    # No forbidden DDL/DML tokens
    if _FORBIDDEN_TOKENS.search(stripped):
        logger.warning("SQL validation failed: contains forbidden token")
        return False

    return True


def generate_sql(
    client: anthropic.Anthropic,
    user_query: str,
    extracted_filters: dict,
) -> dict:
    """Generate a parameterized SQL query from a natural language question.

    Args:
        client: Anthropic client instance.
        user_query: The natural language question.
        extracted_filters: Filters extracted by the router (dates, names, etc.).

    Returns:
        Dict with keys: sql, params, explanation.
        On error, returns dict with 'error' key.
    """
    t0 = time.time()

    # Include extracted filters as context for the SQL generator
    context = user_query
    if extracted_filters:
        filter_info = {k: v for k, v in extracted_filters.items() if v}
        if filter_info:
            context += f"\n\n[Extracted filters: {json.dumps(filter_info)}]"

    try:
        response = client.messages.create(
            model=SQL_GEN_MODEL,
            max_tokens=1024,
            system=SQL_GEN_SYSTEM_PROMPT,
            messages=[{"role": "user", "content": context}],
        )

        text = ""
        for block in response.content:
            if block.type == "text":
                text += block.text

        # Strip markdown code fences if present
        match = re.search(r"```(?:json)?\s*\n?(.*?)\n?```", text, re.DOTALL)
        if match:
            text = match.group(1)

        result = json.loads(text.strip())

        sql = result.get("sql", "")
        params = result.get("params", [TENANT_ID])
        explanation = result.get("explanation", "")

        elapsed = time.time() - t0
        logger.info("SQL generation (%.1fs): %s", elapsed, explanation)

        return {"sql": sql, "params": params, "explanation": explanation}

    except Exception as exc:
        elapsed = time.time() - t0
        logger.warning("SQL generation failed (%.1fs): %s", elapsed, exc)
        return {"error": f"SQL generation failed: {exc}"}


async def execute_database_query(
    pool: asyncpg.Pool,
    user_query: str,
    client: anthropic.Anthropic,
    extracted_filters: dict,
) -> dict:
    """Generate, validate, execute SQL, and synthesize a natural language answer.

    Args:
        pool: asyncpg connection pool.
        user_query: The original user question.
        client: Anthropic client for SQL generation and answer synthesis.
        extracted_filters: Filters from the router.

    Returns:
        Dict with keys: answer, sql_used, row_count.
        On error, returns dict with 'error' key.
    """
    # 1. Generate SQL
    gen_result = generate_sql(client, user_query, extracted_filters)
    if "error" in gen_result:
        return gen_result

    sql = gen_result["sql"]
    params = gen_result["params"]

    # 2. Validate SQL
    if not validate_sql(sql):
        return {"error": f"Generated SQL failed safety validation: {sql[:200]}"}

    # 3. Execute
    try:
        async with pool.acquire() as conn:
            rows = await conn.fetch(sql, *params)
    except Exception as exc:
        logger.warning("SQL execution failed: %s\nSQL: %s\nParams: %s", exc, sql, params)
        return {"error": f"SQL execution failed: {exc}"}

    # Limit rows
    rows = rows[:MAX_ROWS]
    row_count = len(rows)

    # Convert to list of dicts for serialization
    results = []
    for row in rows:
        row_dict = {}
        for key, value in dict(row).items():
            # Handle non-JSON-serializable types
            if hasattr(value, "isoformat"):
                row_dict[key] = value.isoformat()
            elif isinstance(value, (int, float, str, bool, type(None))):
                row_dict[key] = value
            else:
                row_dict[key] = str(value)
        results.append(row_dict)

    # 4. Synthesize natural language answer
    try:
        synthesis_prompt = (
            f"The user asked: {user_query}\n\n"
            f"SQL executed: {sql}\n\n"
            f"Results ({row_count} rows):\n{json.dumps(results, indent=2)}\n\n"
            "Provide a clear, natural language answer to the user's question based on "
            "these database results. Be specific with numbers and dates. If the results "
            "are empty, say so clearly."
        )

        response = client.messages.create(
            model=SQL_GEN_MODEL,
            max_tokens=1024,
            system=(
                "You are a helpful assistant answering questions about Kent School District "
                "board meeting records. Provide concise, factual answers based on the "
                "database query results provided."
            ),
            messages=[{"role": "user", "content": synthesis_prompt}],
        )

        answer = ""
        for block in response.content:
            if block.type == "text":
                answer += block.text

    except Exception as exc:
        logger.warning("Answer synthesis failed: %s", exc)
        # Fall back to raw results
        answer = f"Query returned {row_count} results:\n{json.dumps(results, indent=2)}"

    return {
        "answer": answer,
        "sql_used": sql,
        "row_count": row_count,
    }


async def execute_scoped_database_query(
    pool: asyncpg.Pool,
    user_query: str,
    client: anthropic.Anthropic,
    extracted_filters: dict,
    document_ids: list[str],
) -> str | None:
    """Run a database query scoped to specific document IDs (for hybrid route).

    Returns a text summary of the database results, or None on failure.
    """
    if not document_ids:
        return None

    # Build a context hint for the SQL generator
    scoped_query = (
        f"{user_query}\n\n"
        f"[IMPORTANT: Scope the query to ONLY these document IDs using "
        f"WHERE d.id = ANY($N::uuid[]): {document_ids[:20]}]"
    )

    gen_result = generate_sql(client, scoped_query, extracted_filters)
    if "error" in gen_result:
        logger.warning("Scoped SQL generation failed: %s", gen_result["error"])
        return None

    sql = gen_result["sql"]
    params = gen_result["params"]

    if not validate_sql(sql):
        logger.warning("Scoped SQL failed validation: %s", sql[:200])
        return None

    try:
        async with pool.acquire() as conn:
            rows = await conn.fetch(sql, *params)
    except Exception as exc:
        logger.warning("Scoped SQL execution failed: %s", exc)
        return None

    rows = rows[:MAX_ROWS]
    if not rows:
        return None

    results = []
    for row in rows:
        row_dict = {}
        for key, value in dict(row).items():
            if hasattr(value, "isoformat"):
                row_dict[key] = value.isoformat()
            elif isinstance(value, (int, float, str, bool, type(None))):
                row_dict[key] = value
            else:
                row_dict[key] = str(value)
        results.append(row_dict)

    return (
        f"\n\n--- Additional structured data ---\n"
        f"Database query results ({len(results)} rows):\n"
        f"{json.dumps(results, indent=2)}"
    )
