"""Build the voucher fact tables from the source PDFs.

Reads ``documents`` read-only, reads PDFs from every corpus and staging
root, and writes only to schema ``facts``.

Two things here are deliberate and worth reading before changing:

**Fund comes from the printed header, not the file name, wherever the
header exists.** ``TVF_Vouchers_02-11-26.pdf`` prints ``Permanent Fund
Warrants``. The file name is typed by a person; the header is generated by
the accounting system.

**"Cumulative" is measured, not inferred from the era.** Phase 0 found that
the 2021-02-10 and 2021-03-10 Transportation listings both total
$1,175,094.00 while their recaps state $783,396.00 and $391,698.00 -- the
listing restates prior cycles. It is tempting to tag a whole era as
cumulative, but the Era C column header is still in use in 2026, so an era
label would wrongly brand current sets. Instead each set is compared against
earlier sets of the same fund by check number, and the overlap is recorded
as a fact about that set.

No LLM is involved in any amount, date, vendor, check-number or total path.
"""

from __future__ import annotations

import argparse
import re
import sys
from collections import defaultdict
from dataclasses import dataclass, field
from datetime import date
from decimal import Decimal

import census
import db
import psycopg2.extras
from classify import fund_from_text
from locators import PdfText, make_quote, source_kind
from parsers import COLUMN_AMBIGUOUS, ParsedListing, parse_listing_geometric, parse_register
from psycopg2 import sql
from vendors import is_person_shaped, normalize_vendor

# P-card pseudo-checks begin 926; payroll warrants are 530xxx. Both were
# confirmed against the 2026 sets rather than assumed from the brief.
PCARD_PREFIX = "926"
PAYROLL_PREFIX = "530"

# A check number this corpus uses as a sentinel for a credit rather than as
# an actual warrant. Confirmed on 2026-05-27 ACH: check 8888888888,
# Electrocom Inc, six rows summing to zero invoice against -$2,887.19.
#
# This set drives is_credit ONLY, and is deliberately still a literal set.
# Widening it to the pattern below would newly mark 8888888898 and
# 8888888899 -- two positive Dept of Revenue AP source invoices on
# 2025-02-26 GF -- as credits, which they are not.
SENTINEL_CHECK_NUMBERS = {"8888888888", "9999999999"}

# What counts as a sentinel for the purposes of the DEDUPE KEY: a number
# that is all one digit, or that carries a run of eight or more identical
# digits. Three numbers in the corpus match -- 8888888888 (six rows) and
# 8888888898 / 8888888899 (one row each) -- and a literal set of two would
# have missed the latter pair. They are not warrant identifiers: the
# accounting system emits them for entries that have no warrant, so the same
# number can be reused for unrelated payments in unrelated cycles.
#
# Separate from SENTINEL_CHECK_NUMBERS on purpose. "Not a warrant
# identifier" and "is a credit" are different claims about a row, and the
# 2025-02-26 pair is the proof: sentinel-shaped and positive.
SENTINEL_CHECK_RX = re.compile(r"^(\d)\1*$|(\d)\2{7,}")


def is_sentinel_check(number: str | None) -> bool:
    """Whether a check number is a sentinel rather than a warrant identifier.

    Args:
        number: Check number as printed, or None.

    Returns:
        True when the number is all one digit or carries a run of eight or
        more identical digits.
    """
    return bool(number) and bool(SENTINEL_CHECK_RX.search(number))


@dataclass
class SetRow:
    """One voucher set, ready to write.

    Attributes:
        set_id: Stable identifier, ``<meeting_date>:<fund>``.
        artifact: The census artifact it came from.
        parsed: The parser's output.
        lines: Parsed line rows.
        unread_lines: Rows held with a reason code rather than parsed.
    """

    set_id: str
    artifact: object
    parsed: ParsedListing
    lines: list = field(default_factory=list)
    stated_total: Decimal | None = None
    parsed_total: Decimal = Decimal("0")
    sum_check_dedup: Decimal = Decimal("0")
    check_count: int = 0
    hash_total: int = 0
    reconciled: bool | None = None
    delta: Decimal | None = None
    reason_code: str | None = None
    notes: list[str] = field(default_factory=list)
    fund: str | None = None
    stated_total_page: int | None = None
    unread_lines: int = 0
    # Phase 1 measurements, reported per set rather than recomputed later.
    paren_rows: int = 0
    paren_total: Decimal = Decimal("0")
    paren_rows_held: int = 0
    sentinel_rows: int = 0


def choose_fund(artifact, parsed: ParsedListing, first_page: str) -> tuple[str | None, str | None]:
    """Decide a set's fund, preferring the printed header over the file name.

    Args:
        artifact: Census artifact carrying the title-derived fund.
        parsed: Parser output (unused today; kept for symmetry).
        first_page: Text of page 1.

    Returns:
        ``(fund, note)`` where note is set when the two signals disagree.
    """
    from_text = fund_from_text(first_page)
    from_title = artifact.fund
    if from_text and from_title and from_text != from_title:
        return from_text, (
            f"fund disagreement: file name says {from_title}, printed header says {from_text}; the header wins"
        )
    return (from_text or from_title), None


def build_lines(set_id: str, artifact, parsed: ParsedListing, pdf: PdfText) -> list[dict]:
    """Turn parsed rows into ``facts.voucher_line`` dicts.

    Args:
        set_id: Owning set.
        artifact: Census artifact, for provenance.
        parsed: Parser output.
        pdf: The extracted PDF, for page lookup.

    Returns:
        One dict per line, in document order.
    """
    source = source_kind(artifact.resolved_path)
    out: list[dict] = []
    for seq, row in enumerate(parsed.rows, start=1):
        number = row.check_number or ""
        quote = make_quote(pdf.text, row.char_offset, row.char_end) or (row.line_text.strip()[:300] or "(blank row)")
        out.append(
            {
                "set_id": set_id,
                "line_seq": seq,
                "vendor_raw": row.vendor_raw,
                "vendor_norm": normalize_vendor(row.vendor_raw),
                "check_date": row.check_date,
                "check_number": row.check_number,
                "check_amount": row.check_amount,
                "invoice_amount": row.invoice_amount,
                "description": row.description or None,
                "is_pcard": number.startswith(PCARD_PREFIX),
                "is_payroll_warrant": number.startswith(PAYROLL_PREFIX) and len(number) == 6,
                "is_person_shaped": is_person_shaped(row.vendor_raw),
                "is_credit": (row.invoice_amount is not None and row.invoice_amount < 0)
                or number in SENTINEL_CHECK_NUMBERS,
                "amount_paren": row.amount_paren,
                "reason_code": row.reason_code,
                "reason_detail": row.reason_detail,
                "regex_verdict": row.regex_verdict,
                "source": source,
                "locator_document_id": artifact.document_id,
                "locator_file_path": artifact.resolved_path,
                "locator_file_sha256": artifact.sha256,
                "locator_page": pdf.page_for_offset(row.char_offset),
                "locator_char_offset": row.char_offset,
                "locator_quote": quote,
            }
        )
    return out


def dedupe_key(number: str | None) -> str | None:
    """Return the key a check number contributes to a dedupe, or None.

    A sentinel number is not a warrant identifier. ``8888888888`` is used by
    this corpus to mark a credit and ``9999999999`` likewise, so the same
    sentinel appears on unrelated payments in unrelated cycles. Collapsing
    them on ``(fund, check_number)`` would merge payments that have nothing
    to do with each other and would silently remove real money from a
    cross-cycle total. Sentinels are therefore excluded from the key and
    each sentinel row counts as its own payment.

    Args:
        number: Check number as printed, or None.

    Returns:
        The number when it may be used as a dedupe key, otherwise None.
    """
    if not number or is_sentinel_check(number):
        return None
    return number


def _impossible_total(stated: Decimal, negatives: Decimal, largest: Decimal | None, unread: int) -> str | None:
    """Say why a printed TOTAL cannot be produced by the rows beneath it.

    One rule, and it is deliberately the only one, because it is the only
    direction of disagreement a parse failure cannot imitate:

        every printed row was read, none of them is negative, and the
        printed TOTAL is smaller than one single row.

    A sum of non-negative numbers is at least as large as its largest term.
    So under these conditions no reading of these rows -- and no row this
    layer might have missed, since it missed none -- produces this TOTAL.
    The document disagrees with itself.

    The mirror-image test, "the TOTAL is larger than the sum of the rows",
    is **not** used and must not be added. That is precisely the signature
    of an incomplete parse: rows the layer failed to read are missing from
    the sum, and calling that a source error would blame the district for a
    defect in this code. It is what OUT_OF_BALANCE is for.

    The ``unread`` guard carries the same argument. With even one row held
    unread, a negative row could be sitting in it, and the impossibility
    claim would rest on rows this layer admits it could not read.

    Args:
        stated: The printed TOTAL.
        negatives: Sum of the negative invoice amounts (zero or less).
        largest: The largest single invoice amount, or None when there are
            no readable rows.
        unread: How many printed rows could not be read.

    Returns:
        A sentence naming the impossibility, or None when the TOTAL is
        arithmetically reachable.
    """
    if unread or negatives != 0 or largest is None:
        return None
    if stated < largest:
        return (
            f"the printed TOTAL {stated} is smaller than a single line in the set ({largest}); every printed "
            f"row was read and none is negative, so there is nothing that could have been subtracted"
        )
    return None


def summarize(row: SetRow) -> None:
    """Compute the three control totals and the reconciliation verdict.

    ``reconciled`` has three states and they are not interchangeable:
    true when the lines sum to a stated total to the cent, false when they
    sum to something else, and NULL when the document states no total to
    reconcile against. 303 listings from 2017-2022 are in the third case,
    and marking them false would assert the district's arithmetic is wrong
    when what is true is that the document states no arithmetic.

    Parenthesised amounts are read as negative, but the reading is
    **adopted per set and only on the document's own evidence**: it stands
    where the printed TOTAL then ties to the cent, and where instead the
    TOTAL ties with those rows held unread, the rows are held. A sign
    convention is a claim about what the district meant, and the only
    witness available is the arithmetic it printed.

    Args:
        row: The set to summarize, mutated in place.
    """
    seen: dict[str, Decimal] = {}
    sentinel_rows = 0
    total = Decimal("0")
    paren_total = Decimal("0")
    paren_rows = 0
    negatives = Decimal("0")
    largest: Decimal | None = None
    for line in row.lines:
        # A row that could not be read contributes nothing to any control
        # total. It is counted, held and reported -- never summed as if it
        # were zero and never silently dropped.
        if line["reason_code"] is not None:
            row.unread_lines += 1
            continue
        amount = line["invoice_amount"]
        if amount is not None:
            total += amount
            if amount < 0:
                negatives += amount
            largest = amount if largest is None else max(largest, amount)
        if line["amount_paren"]:
            paren_rows += 1
            paren_total += amount or Decimal("0")
        number = line["check_number"]
        key = dedupe_key(number)
        if key is None:
            # Sentinel or absent: its own payment, never merged with another.
            if number:
                sentinel_rows += 1
                row.sum_check_dedup += line["check_amount"] or Decimal("0")
                row.check_count += 1
        elif key not in seen:
            seen[key] = line["check_amount"] or Decimal("0")
            if key.isdigit():
                row.hash_total += int(key)
    row.parsed_total = total
    row.sum_check_dedup += sum(seen.values(), Decimal("0"))
    row.check_count += len(seen)
    row.paren_rows = paren_rows
    row.paren_total = paren_total
    row.sentinel_rows = sentinel_rows
    row.stated_total = row.parsed.stated_total
    if row.unread_lines:
        row.notes.append(
            f"{row.unread_lines} of {len(row.lines)} printed rows could not be assigned to columns and are "
            f"held with reason code {COLUMN_AMBIGUOUS}; they are excluded from every total on this row."
        )
    if sentinel_rows:
        row.notes.append(
            f"{sentinel_rows} row(s) carry a sentinel check number, which this corpus uses to mark a credit "
            f"rather than to identify a warrant. They are excluded from the (fund, check number) dedupe key "
            f"and each counts as its own payment."
        )

    if row.parsed.grid_note and not row.lines:
        row.reconciled = False
        row.reason_code = COLUMN_AMBIGUOUS
        return
    if not row.lines:
        row.reconciled = False
        row.reason_code = "REGEX_MISS"
        return
    if row.unread_lines == len(row.lines):
        row.reconciled = False
        row.reason_code = COLUMN_AMBIGUOUS
        return
    if row.stated_total is None:
        # Nothing to check against. Not a failure of the parse, and not a
        # claim that the set is wrong.
        row.reconciled = None
        row.reason_code = "TOTAL_NOT_FOUND"
        if paren_rows:
            row.notes.append(
                f"{paren_rows} row(s) print an amount in parentheses, read as negative ({paren_total}). "
                f"This listing prints no TOTAL, so the reading could not be confirmed against the document."
            )
        return

    # The parenthesised-amount reading is adopted only where the document's
    # own TOTAL agrees with it. Where the TOTAL instead agrees with those
    # rows held unread, they are held: before this rule existed every such
    # row failed its column check, so holding them is exactly the behaviour
    # the set already had, and a set that reconciled cannot stop.
    if paren_rows and total != row.stated_total and (total - paren_total) == row.stated_total:
        for line in row.lines:
            if line["reason_code"] is None and line["amount_paren"]:
                line["reason_code"] = COLUMN_AMBIGUOUS
                line["reason_detail"] = (
                    "the amount column is printed in parentheses and this set's TOTAL ties only with the row "
                    "held, so the negative reading was not adopted here"
                )
                row.unread_lines += 1
        row.parsed_total = total - paren_total
        row.paren_rows_held = paren_rows
        row.notes.append(
            f"{paren_rows} row(s) print an amount in parentheses. The printed TOTAL ties only with those rows "
            f"held unread, so the negative reading was not adopted for this set."
        )
    elif paren_rows:
        row.notes.append(
            f"{paren_rows} row(s) print an amount in parentheses, read as negative ({paren_total}); "
            + (
                "the printed TOTAL ties to the cent under that reading."
                if total == row.stated_total
                else "the printed TOTAL does not tie under either reading."
            )
        )

    row.delta = row.parsed_total - row.stated_total
    if row.delta == 0:
        row.reconciled = True
        if row.parsed.extra_totals:
            row.notes.append(
                f"{len(row.parsed.extra_totals)} further TOTAL line(s) after the chosen "
                f"one: {', '.join(str(a) for _, a, _ in row.parsed.extra_totals)}. The "
                f"chosen total is the first after the last data row and it reconciles."
            )
        return

    row.reconciled = False
    impossible = _impossible_total(row.stated_total, negatives, largest, row.unread_lines)
    if impossible:
        # A source error, not a parse failure. Keeping it out of
        # OUT_OF_BALANCE is the point: that bucket is where the parse is
        # suspect, and this set's parse is not what is wrong.
        row.reason_code = "TOTAL_INCONSISTENT_AT_SOURCE"
        row.notes.append(f"source error: {impossible}. The parse is not what is wrong here.")
        return
    row.reason_code = "MULTIPLE_TOTALS" if row.parsed.extra_totals else "OUT_OF_BALANCE"


PERIOD_INVALID_AT_SOURCE = "PERIOD_INVALID_AT_SOURCE"
PERIOD_NOT_STATED = "PERIOD_NOT_STATED"


def apply_period_status(row: SetRow) -> None:
    """Record what the document said about its own warrant period.

    Two facts that were previously silent, and one precedence rule.

    ``PERIOD_INVALID_AT_SOURCE`` -- the listing states a period that ends
    before it begins. **The parsed dates are kept, not blanked.** They are
    what the document printed, and a reader checking this layer against the
    page needs to see the same thing the page shows; blanking them would
    hide the district's error behind what looks like a missing field.

    ``PERIOD_NOT_STATED`` -- no period could be read from the listing's
    header. Previously this was an unexplained NULL. **The note is worded
    carefully and the code name is wider than the fact it records:** some
    era-B and era-C listings do print a period, hyphenated -- "3-9-17
    through 3-16-17" -- which ``PERIOD_RX`` does not match, so they land
    here too. Saying "states none" would be a claim this layer cannot
    support; saying "none could be read" is what is true either way. The
    count of sets in each situation is in the session report.

    **Precedence: neither code is ever written over an existing one.** A
    reconciliation finding outranks a metadata finding -- a set that is out
    of balance has something more important to say than that its header was
    quiet -- and ``reason_code`` holds one value. The invariant itself is
    asserted independently of this field by ``check_period_invariant`` in
    ``fixtures.py``, so nothing depends on the code winning the slot.

    Args:
        row: The set to annotate, mutated in place.
    """
    start, end = row.parsed.period
    if start is not None and end is not None and end < start:
        row.notes.append(
            f"source error: this listing states a warrant period of {start} through {end}, which ends "
            f"before it begins. The dates are recorded exactly as printed; the parse is not what is wrong here."
        )
        if row.reason_code is None:
            row.reason_code = PERIOD_INVALID_AT_SOURCE
        return
    if start is None and end is None:
        row.notes.append(
            "no warrant period could be read from this listing's header, so none is recorded for it. "
            "Either the listing prints none, or it prints one in a format this layer does not read."
        )
        if row.reason_code is None:
            row.reason_code = PERIOD_NOT_STATED


def mark_cumulative(sets: list[SetRow]) -> None:
    """Record, per set, how many of its checks appeared in an earlier set.

    A listing that restates prior cycles is not an error, but summing such
    listings across meetings double-counts real money. The overlap is
    measured by check number against every earlier set of the same fund, so
    the finding is a property of the document rather than of its era.

    Args:
        sets: All sets, any order. Mutated in place.
    """
    by_fund: dict[str, list[SetRow]] = defaultdict(list)
    for row in sets:
        if row.fund:
            by_fund[row.fund].append(row)

    for fund, rows in by_fund.items():
        rows.sort(key=lambda r: r.artifact.meeting_date or "")
        seen: set[str] = set()
        for row in rows:
            # Sentinels are excluded here for the same reason they are
            # excluded from the dedupe key: the same sentinel on two cycles
            # is two unrelated credits, not one restated warrant, and
            # counting it as restated would understate real money.
            numbers = {k for line in row.lines if (k := dedupe_key(line["check_number"]))}
            repeated = numbers & seen
            if repeated:
                repeated_amount = sum(
                    (line["invoice_amount"] or Decimal("0") for line in row.lines if line["check_number"] in repeated),
                    Decimal("0"),
                )
                row.notes.append(
                    f"cumulative: {len(repeated)} of {len(numbers)} check numbers "
                    f"({repeated_amount} of {row.parsed_total}) already appeared in an "
                    f"earlier {fund} set. Summing this set with earlier ones "
                    f"double-counts that money."
                )
            seen |= numbers


def _no_register(row: SetRow, reason: str, path: str | None, sha: str | None) -> dict:
    """Record that a set has no usable register to be checked against.

    The absence is stored rather than left implicit. A reader looking at
    2026-06-24 or 2026-07-22 needs to know that the signed register for
    those nights is a scan with no text layer, so the listing is the only
    machine-readable source and the figure has no second opinion behind it.

    Args:
        row: The set.
        reason: ``REGISTER_NOT_FOUND`` or ``REGISTER_NO_TEXT``.
        path: Path of the register that exists but cannot be read.
        sha: Digest of that register.

    Returns:
        A reconciliation dict with no comparison in it.
    """
    return {
        "set_id": row.set_id,
        # The basis that WOULD have applied. Saying which comparison is
        # missing is more use than saying only that one is.
        "basis": "ap_direct_deposit" if row.fund == "ACH" else "warrants_plus_pcard",
        "register_document_id": None,
        "register_file_path": path,
        "register_file_sha256": sha,
        "register_total": None,
        "register_warrant_range": None,
        "detail_total": row.parsed_total,
        "match": None,
        "delta": None,
        "reason": reason,
        "notes": (
            "The signed register for this meeting has no extractable text layer, so the listing is the only "
            "machine-readable source for this set."
            if reason == "REGISTER_NO_TEXT"
            else "No signed register or warrant recap for this meeting is on this machine."
        ),
        "locator_detail_page": None,
        "locator_detail_char_offset": row.parsed.stated_total_offset,
        "locator_detail_quote": None,
        "locator_register_page": None,
        "locator_register_char_offset": None,
        "locator_register_quote": None,
    }


def reconcile_against_register(
    sets_by_date: dict[str, list[SetRow]],
    registers: dict[str, list[dict]],
    recaps: dict[str, list[dict]],
    unreadable: dict[str, tuple[str, str | None]] | None = None,
) -> list[dict]:
    """Cross-check each set against the signed register, where one exists.

    Three bases are computed, and which one applies depends on the fund:

    ``ap_direct_deposit``
        The ACH listing total equals the sum of every accounts-payable
        direct-deposit line in the register, across all funds. Verified
        exactly on 2026-03-25.
    ``warrants_plus_pcard``
        A fund listing equals that fund's accounts-payable warrant ranges
        plus its purchasing-card line. Exact for Capital on 2026-03-25;
        ASB differs by two warrants that are on the register and not in the
        listing, which is the kind of fact this table exists to hold.
    ``recap_fund_total``
        Where no register exists but a Warrant Recap does, its per-fund
        total is recorded. The recap is register scope, so equality is not
        expected for funds that carry payroll or electronic transfers.

    Args:
        sets_by_date: Sets grouped by meeting date.
        registers: Parsed registers, keyed by meeting date.
        recaps: Parsed recap fund totals, keyed by meeting date.
        unreadable: Meeting dates whose register exists but carries no text
            layer, mapped to ``(path, sha256)``.

    Returns:
        ``facts.voucher_reconciliation`` dicts.
    """
    unreadable = unreadable or {}
    out: list[dict] = []
    for meeting_date, rows in sets_by_date.items():
        register = registers.get(meeting_date)
        recap = recaps.get(meeting_date)
        for row in rows:
            if row.fund is None or not row.lines:
                continue
            record = None
            if register:
                record = _register_basis(row, register)
            elif recap:
                record = _recap_basis(row, recap)
            if record:
                out.append(record)
                continue
            if meeting_date in unreadable:
                path, sha = unreadable[meeting_date]
                out.append(_no_register(row, "REGISTER_NO_TEXT", path, sha))
            elif not register and not recap:
                out.append(_no_register(row, "REGISTER_NOT_FOUND", None, None))
    return out


def _register_basis(row: SetRow, register: dict) -> dict | None:
    """Compare one set against the signed register.

    Args:
        row: The set.
        register: Parsed register, with ``lines`` and ``fund_totals``.

    Returns:
        A reconciliation dict, or None when no basis applies.
    """
    lines = register["lines"]
    meta = register["meta"]
    if row.fund == "ACH":
        relevant = [line for line in lines if line["is_direct_deposit"] and line["is_accounts_payable"]]
        basis = "ap_direct_deposit"
        ranges = None
    else:
        # The listing holds warrants and P-card pseudo-checks. It does NOT
        # hold the register's other electronic transfers -- DOR use taxes,
        # L&I self-insurance, direct deposits -- so the basis is exactly the
        # lines that carry a warrant range, plus the purchasing-card line.
        # Phase 0 proved this basis ties Capital to the cent on 2026-03-25
        # and leaves ASB short by exactly two warrants that the register
        # carries and the listing does not.
        relevant = [
            line
            for line in lines
            if line["fund"] == row.fund
            and not line["is_payroll"]
            and line["is_accounts_payable"]
            and (line["warrant_range"] or line["is_pcard"])
        ]
        basis = "warrants_plus_pcard"
        ranges = ",".join(line["warrant_range"] for line in relevant if line["warrant_range"]) or None
    if not relevant:
        return None
    register_total = sum((line["amount"] for line in relevant), Decimal("0"))
    delta = row.parsed_total - register_total
    first = relevant[0]
    return {
        "set_id": row.set_id,
        "basis": basis,
        "register_document_id": meta["document_id"],
        "register_file_path": meta["path"],
        "register_file_sha256": meta["sha256"],
        "register_total": register_total,
        "register_warrant_range": ranges,
        "detail_total": row.parsed_total,
        "match": delta == 0,
        "delta": delta,
        "reason": "MATCH" if delta == 0 else "REGISTER_MISMATCH",
        "notes": None
        if delta == 0
        else (
            f"{len(relevant)} register line(s) totalling {register_total} against a "
            f"listing of {row.parsed_total}. Recorded, not resolved."
        ),
        # The set's own TOTAL locator lives on facts.voucher_set; here only
        # the offset is repeated, so the two sides can be read together.
        "locator_detail_page": None,
        "locator_detail_char_offset": row.parsed.stated_total_offset,
        "locator_detail_quote": None,
        "locator_register_page": meta["page_for_offset"](first["offset"]),
        "locator_register_char_offset": first["offset"],
        "locator_register_quote": first["text"][:300],
    }


def _recap_basis(row: SetRow, recap: dict) -> dict | None:
    """Compare one set against a Warrant Recap fund total.

    Args:
        row: The set.
        recap: Parsed recap, with ``fund_totals`` and ``meta``.

    Returns:
        A reconciliation dict, or None when the recap names no such fund.
    """
    meta = recap["meta"]
    match = next((t for t in recap["fund_totals"] if t["fund"] == row.fund), None)
    if match is None:
        return None
    delta = row.parsed_total - match["amount"]
    return {
        "set_id": row.set_id,
        "basis": "recap_fund_total",
        "register_document_id": meta["document_id"],
        "register_file_path": meta["path"],
        "register_file_sha256": meta["sha256"],
        "register_total": match["amount"],
        "register_warrant_range": None,
        "detail_total": row.parsed_total,
        "match": delta == 0,
        "delta": delta,
        # The recap is register scope: it includes payroll and electronic
        # transfers the listing never shows. A difference is expected for
        # funds that carry them, so it is not called a mismatch.
        "reason": "MATCH" if delta == 0 else "SCOPE_DIFFERS",
        "notes": "Warrant Recap totals are register scope, not listing scope.",
        "locator_detail_page": None,
        "locator_detail_char_offset": row.parsed.stated_total_offset,
        "locator_detail_quote": None,
        "locator_register_page": meta["page_for_offset"](match["offset"]),
        "locator_register_char_offset": match["offset"],
        "locator_register_quote": match["quote"],
    }


def build_vendors(all_lines: list[dict], set_dates: dict[str, date]) -> list[dict]:
    """Aggregate ``facts.vendor`` from the parsed lines.

    Args:
        all_lines: Every voucher line.
        set_dates: Meeting date of each set.

    Returns:
        One dict per distinct ``vendor_norm``.
    """
    agg: dict[str, dict] = {}
    for line in all_lines:
        # A row that could not be read has no vendor to aggregate: its
        # vendor_raw is whatever text was on the page. Letting it through
        # would invent vendors out of unparsed rows.
        if line["reason_code"] is not None:
            continue
        norm = line["vendor_norm"]
        entry = agg.get(norm)
        when = set_dates.get(line["set_id"])
        if entry is None:
            entry = agg[norm] = {
                "vendor_norm": norm,
                "display_name": line["vendor_raw"],
                "aliases": set(),
                "is_person_shaped": line["is_person_shaped"],
                "first_seen": when,
                "last_seen": when,
                "line_count": 0,
                "total_invoice": Decimal("0"),
                "observed_locator_document_id": line["locator_document_id"],
                "observed_locator_file_path": line["locator_file_path"],
                "observed_locator_file_sha256": line["locator_file_sha256"],
                "observed_locator_page": line["locator_page"],
                "observed_locator_char_offset": line["locator_char_offset"],
                "observed_locator_quote": line["locator_quote"],
            }
        entry["aliases"].add(line["vendor_raw"])
        entry["line_count"] += 1
        if line["invoice_amount"] is not None:
            entry["total_invoice"] += line["invoice_amount"]
        if when:
            if entry["first_seen"] is None or when < entry["first_seen"]:
                entry["first_seen"] = when
            if entry["last_seen"] is None or when > entry["last_seen"]:
                entry["last_seen"] = when
    for entry in agg.values():
        # The display name is the most common spelling, chosen by frequency
        # only -- never edited, never title-cased. "KCDA" must not become
        # "Kcda".
        entry["aliases"] = sorted(entry["aliases"])
        entry["display_name"] = max(entry["aliases"], key=len) if entry["aliases"] else entry["display_name"]
    return list(agg.values())


SET_COLUMNS = (
    "set_id",
    "meeting_date",
    "fund",
    "source_document_id",
    "agenda_item_document_id",
    "doc_class",
    "format_era",
    "period_start",
    "period_end",
    "pcard_period_start",
    "pcard_period_end",
    "stated_total",
    "parsed_total",
    "sum_check_dedup",
    "line_count",
    "check_count",
    "hash_total",
    "reconciled",
    "delta",
    "reason_code",
    "notes",
    "source",
    "locator_document_id",
    "locator_file_path",
    "locator_file_sha256",
    "locator_page",
    "locator_char_offset",
    "locator_quote",
)

LINE_COLUMNS = (
    "set_id",
    "line_seq",
    "vendor_raw",
    "vendor_norm",
    "check_date",
    "check_number",
    "check_amount",
    "invoice_amount",
    "description",
    "is_pcard",
    "is_payroll_warrant",
    "is_person_shaped",
    "is_credit",
    "amount_paren",
    "reason_code",
    "reason_detail",
    "regex_verdict",
    "source",
    "locator_document_id",
    "locator_file_path",
    "locator_file_sha256",
    "locator_page",
    "locator_char_offset",
    "locator_quote",
)

VENDOR_COLUMNS = (
    "vendor_norm",
    "display_name",
    "aliases",
    "is_person_shaped",
    "first_seen",
    "last_seen",
    "line_count",
    "total_invoice",
    "observed_locator_document_id",
    "observed_locator_file_path",
    "observed_locator_file_sha256",
    "observed_locator_page",
    "observed_locator_char_offset",
    "observed_locator_quote",
)

RECON_COLUMNS = (
    "set_id",
    "basis",
    "register_document_id",
    "register_file_path",
    "register_file_sha256",
    "register_total",
    "register_warrant_range",
    "detail_total",
    "match",
    "delta",
    "reason",
    "notes",
    "locator_detail_page",
    "locator_detail_char_offset",
    "locator_detail_quote",
    "locator_register_page",
    "locator_register_char_offset",
    "locator_register_quote",
)

LOG_COLUMNS = (
    "file_sha256",
    "file_path",
    "document_id",
    "meeting_date",
    "fund",
    "doc_class",
    "format_era",
    "status",
    "pages",
    "lines_found",
    "checks_found",
    "note",
    "source",
    "grid_schema",
    "grid_method",
    "unread_lines",
    "regex_agree",
    "regex_disagree",
    "regex_miss",
)


def _insert(cursor, schema: str, table: str, columns: tuple[str, ...], rows: list[dict]) -> None:
    """Insert rows with parameter binding, in batches.

    The statement is composed with ``psycopg2.sql`` identifier quoting rather
    than string formatting. The schema, table and column names here are all
    module-level literals and could not carry input, but SQL built by string
    formatting is forbidden in this project regardless of provenance -- the
    rule is worth more than the one exception would save.

    Args:
        cursor: An open psycopg2 cursor.
        schema: Schema name.
        table: Table name.
        columns: Column names, in order.
        rows: Row dicts.
    """
    if not rows:
        return
    statement = sql.SQL("INSERT INTO {}.{} ({}) VALUES %s").format(
        sql.Identifier(schema),
        sql.Identifier(table),
        sql.SQL(", ").join(sql.Identifier(column) for column in columns),
    )
    values = [tuple(row.get(column) for column in columns) for row in rows]
    psycopg2.extras.execute_values(cursor, statement.as_string(cursor), values, page_size=1000)


def main() -> None:
    """Parse every voucher artifact and load schema ``facts``."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--reload", action="store_true", help="delete and rebuild all rows")
    parser.add_argument("--only-date", help="restrict to one meeting date")
    parser.add_argument("--progress", action="store_true", help="progress on stderr")
    parser.add_argument("--dry-run", action="store_true", help="parse but write nothing")
    args = parser.parse_args()

    artifacts = census.merge(census.db_artifacts(db.query_dicts), census.disk_artifacts())
    kept = [a for a in artifacts if a.exclusion is None and a.resolved_path]
    if args.only_date:
        kept = [a for a in kept if a.meeting_date == args.only_date]

    agenda_by_date = {row["meeting_date"]: row["document_id"] for row in census.voucher_agenda_items(db.query_dicts)}

    sets: list[SetRow] = []
    logs: list[dict] = []
    registers: dict[str, dict] = {}
    recaps: dict[str, dict] = {}
    unreadable_registers: dict[str, tuple[str, str | None]] = {}
    used_ids: set[str] = set()

    parseable = [a for a in kept if a.doc_class in {"detail_listing", "warrant_register", "warrant_recap"}]
    for index, artifact in enumerate(parseable, start=1):
        if args.progress and index % 25 == 0:
            print(f"  {index}/{len(parseable)}", file=sys.stderr)
        source = source_kind(artifact.resolved_path)
        base_log = {
            "file_sha256": artifact.sha256,
            "file_path": artifact.resolved_path,
            "document_id": artifact.document_id,
            "meeting_date": artifact.meeting_date,
            "fund": artifact.fund,
            "doc_class": artifact.doc_class,
            "format_era": None,
            "pages": None,
            "lines_found": 0,
            "checks_found": 0,
            "note": None,
            "source": source,
            "grid_schema": None,
            "grid_method": None,
            "unread_lines": 0,
            "regex_agree": 0,
            "regex_disagree": 0,
            "regex_miss": 0,
        }
        try:
            # Geometry is only read for detail listings. The register and
            # the recap are parsed as text lines, and reading coordinates
            # for them would cost time for nothing.
            pdf = PdfText(artifact.resolved_path, geometry_too=artifact.doc_class == "detail_listing")
        except Exception as exc:  # noqa: BLE001 - a corrupt PDF is data, not a crash
            logs.append({**base_log, "status": "unreadable", "note": f"{type(exc).__name__}: {exc}"})
            continue
        base_log["pages"] = pdf.page_count
        if not pdf.has_text_layer:
            if artifact.doc_class == "warrant_register" and artifact.meeting_date:
                unreadable_registers[artifact.meeting_date] = (artifact.resolved_path, artifact.sha256)
            logs.append({**base_log, "status": "no_text_layer"})
            continue

        first_page = pdf.pages[0].text if pdf.pages else ""

        if artifact.doc_class == "warrant_register":
            parsed_register = parse_register(pdf.text)
            parsed_register["meta"] = {
                "document_id": artifact.document_id,
                "path": artifact.resolved_path,
                "sha256": artifact.sha256,
                "page_for_offset": pdf.page_for_offset,
            }
            if artifact.meeting_date:
                registers[artifact.meeting_date] = parsed_register
            logs.append(
                {
                    **base_log,
                    "status": "parsed",
                    "lines_found": len(parsed_register["lines"]),
                }
            )
            continue

        if artifact.doc_class == "warrant_recap":
            parsed_recap = parse_register(pdf.text)
            parsed_recap["meta"] = {
                "document_id": artifact.document_id,
                "path": artifact.resolved_path,
                "sha256": artifact.sha256,
                "page_for_offset": pdf.page_for_offset,
            }
            if artifact.meeting_date and parsed_recap["fund_totals"]:
                recaps[artifact.meeting_date] = parsed_recap
            logs.append(
                {
                    **base_log,
                    "status": "parsed" if parsed_recap["fund_totals"] else "total_not_found",
                    "lines_found": len(parsed_recap["fund_totals"]),
                }
            )
            continue

        parsed = parse_listing_geometric(pdf, artifact.meeting_date)
        base_log["format_era"] = parsed.era
        if parsed.era is None:
            logs.append({**base_log, "status": "era_unmatched"})
            continue

        fund, note = choose_fund(artifact, parsed, first_page)
        if fund is None:
            logs.append({**base_log, "status": "skipped", "note": "no fund could be determined"})
            continue

        set_id = f"{artifact.meeting_date}:{fund}"
        suffix = 2
        duplicate = False
        while set_id in used_ids:
            set_id = f"{artifact.meeting_date}:{fund}#{suffix}"
            suffix += 1
            duplicate = True
        used_ids.add(set_id)

        row = SetRow(set_id=set_id, artifact=artifact, parsed=parsed, fund=fund)
        if parsed.stated_total_offset is not None:
            row.stated_total_page = pdf.page_for_offset(parsed.stated_total_offset)
        row.lines = build_lines(set_id, artifact, parsed, pdf)
        if note:
            row.notes.append(note)
        if duplicate:
            row.notes.append("a second listing for this fund and meeting; both are kept because their contents differ")
        summarize(row)
        if duplicate and row.reason_code is None:
            row.reason_code = "DUPLICATE_SET"
        apply_period_status(row)
        sets.append(row)

        if row.reason_code == COLUMN_AMBIGUOUS:
            status = "column_ambiguous"
        elif row.reason_code == "TOTAL_INCONSISTENT_AT_SOURCE":
            status = "total_inconsistent_at_source"
        elif row.reason_code == PERIOD_INVALID_AT_SOURCE:
            status = "period_invalid_at_source"
        elif row.reason_code == PERIOD_NOT_STATED:
            status = "period_not_stated"
        else:
            status = {
                True: "parsed",
                False: "out_of_balance" if row.lines else "regex_miss",
                None: "total_not_found",
            }[row.reconciled]
        logs.append(
            {
                **base_log,
                "fund": fund,
                "status": status,
                "lines_found": len(row.lines),
                "checks_found": row.check_count,
                "note": "; ".join(row.notes) or parsed.grid_note,
                "grid_schema": parsed.grid_schema,
                "grid_method": parsed.grid_method,
                "unread_lines": row.unread_lines,
                "regex_agree": parsed.regex_agree,
                "regex_disagree": parsed.regex_disagree,
                "regex_miss": parsed.regex_miss,
            }
        )

    mark_cumulative(sets)

    sets_by_date: dict[str, list[SetRow]] = defaultdict(list)
    for row in sets:
        sets_by_date[row.artifact.meeting_date].append(row)
    recon_rows = reconcile_against_register(sets_by_date, registers, recaps, unreadable_registers)

    all_lines = [line for row in sets for line in row.lines]
    set_dates = {row.set_id: date.fromisoformat(row.artifact.meeting_date) for row in sets if row.artifact.meeting_date}
    vendors = build_vendors(all_lines, set_dates)

    set_rows = [
        {
            "set_id": row.set_id,
            "meeting_date": row.artifact.meeting_date,
            "fund": row.fund,
            "source_document_id": row.artifact.document_id,
            "agenda_item_document_id": agenda_by_date.get(row.artifact.meeting_date),
            "doc_class": row.artifact.doc_class,
            "format_era": row.parsed.era,
            "period_start": row.parsed.period[0],
            "period_end": row.parsed.period[1],
            "pcard_period_start": row.parsed.pcard_period[0],
            "pcard_period_end": row.parsed.pcard_period[1],
            "stated_total": row.stated_total,
            "parsed_total": row.parsed_total,
            "sum_check_dedup": row.sum_check_dedup,
            "line_count": len(row.lines),
            "check_count": row.check_count,
            "hash_total": row.hash_total,
            "reconciled": row.reconciled,
            "delta": row.delta,
            "reason_code": row.reason_code,
            "notes": "; ".join(row.notes) or None,
            "source": source_kind(row.artifact.resolved_path),
            "locator_document_id": row.artifact.document_id,
            "locator_file_path": row.artifact.resolved_path,
            "locator_file_sha256": row.artifact.sha256,
            "locator_page": None,
            "locator_char_offset": row.parsed.stated_total_offset,
            "locator_quote": None,
        }
        for row in sets
    ]
    # Locator page and quote for the TOTAL line, resolved per set. Without
    # the page the export prints an em dash exactly where a director would
    # look to check the number against the document.
    for row, out in zip(sets, set_rows, strict=True):
        out["locator_page"] = row.stated_total_page
        if row.parsed.stated_total_offset is None:
            continue
        for label, amount, offset in row.parsed.totals:
            if offset == row.parsed.stated_total_offset:
                out["locator_quote"] = f"{label} {amount}"
                break

    print(
        f"sets={len(set_rows)} lines={len(all_lines)} vendors={len(vendors)} "
        f"reconciliations={len(recon_rows)} parse_log={len(logs)}"
    )
    if args.dry_run:
        for out in sorted(set_rows, key=lambda r: (r["meeting_date"] or "", r["fund"] or "")):
            row = next(r for r in sets if r.set_id == out["set_id"])
            print(
                f"  {out['set_id']:32s} era={out['format_era']} stated={out['stated_total']} "
                f"parsed={out['parsed_total']} delta={out['delta']} lines={out['line_count']} "
                f"unread={row.unread_lines} reconciled={out['reconciled']} reason={out['reason_code']} "
                f"grid={row.parsed.grid_schema}/{row.parsed.grid_method} "
                f"regex(agree/disagree/miss)={row.parsed.regex_agree}/"
                f"{row.parsed.regex_disagree}/{row.parsed.regex_miss}"
            )
        return

    with db.connect() as conn:
        with conn.cursor() as cur:
            if args.reload:
                # Only facts tables. Nothing outside schema facts is touched.
                cur.execute("DELETE FROM facts.voucher_reconciliation")
                cur.execute("DELETE FROM facts.voucher_line")
                cur.execute("DELETE FROM facts.voucher_set")
                cur.execute("DELETE FROM facts.vendor")
                cur.execute("DELETE FROM facts.voucher_parse_log")
            _insert(cur, "facts", "voucher_set", SET_COLUMNS, set_rows)
            _insert(cur, "facts", "voucher_line", LINE_COLUMNS, all_lines)
            _insert(cur, "facts", "vendor", VENDOR_COLUMNS, vendors)
            _insert(cur, "facts", "voucher_reconciliation", RECON_COLUMNS, recon_rows)
            _insert(cur, "facts", "voucher_parse_log", LOG_COLUMNS, logs)
    print("loaded")


if __name__ == "__main__":
    main()
